#ifndef FUNCTIONS_H_
#define FUNCTIONS_H_
#include "effector.h"
#include "CASATAWAYANDMUTABLE.h"
#include "STATDEST.h"
#include "COPYCONSTRUCT.h"
void test();
void strfile_test();
void seeking();
void iofile();
void instring();
void ostring();
void walrus();
void strmove();
void format();//
void manips();//流操纵算子
void consttmp();// 
void constp();
void reference();//引用
void refptr();
void ccnocc_test();
void pmep();
void returnEffeciency();
void autuocnt();
void reflex();
void ninherit();
void privinh();
void wind2();
void pvdef();
void polyconstructor();
void multipl();
void multipl3();
void overhead();
void mithis();
void persist1();
void repairinterface();
void c_approach();
void except();
void trmnator();
void cleanup();
void nudep();
void wrapped();
void autoexept();
#endif // !FUNCTIONS_H_
